<a href="https://colab.research.google.com/github/sakshiacharya/present/blob/master/sakshi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! cal

    January 2020      
Su Mo Tu We Th Fr Sa  
          1  2  3  4  
 5  6  7  8  9 10 11  
12 13 14 15 16 17 18  
19 20 21 22 23 24 25  
26 27 28 29 30 31     
                      


In [0]:
# we are going to use Numpy
# pip install numpy -to install in local labs
import numpy as np

In [0]:
#len(dir(np) )
#lets create 1D array
a1=np.array([2,6,76,8])

In [0]:
#creating 2D array
x=np.array([[2,6,7],[3,6,9],[5,1,1]])

In [5]:
x

array([[2, 6, 7],
       [3, 6, 9],
       [5, 1, 1]])

In [6]:
# to print 1st row
x[0]

array([2, 6, 7])

In [7]:
#to print 1st element of 2D array
x[0][0]

2

In [8]:
x[3][1]

IndexError: ignored

In [9]:
#first 2 row
x[0:2]

array([[2, 6, 7],
       [3, 6, 9]])

In [10]:

x[0:,0:2] #1st 2 column

array([[2, 6],
       [3, 6],
       [5, 1]])

In [11]:
#print 1st column
x[0:,0]

array([2, 3, 5])

In [12]:
#task
x[1:3,1:]

array([[6, 9],
       [1, 1]])

In [14]:
#now next task
x[1:3,[0,2]]

array([[3, 9],
       [5, 1]])

In [18]:
#final task
x[1::2,[0,2]]

array([[3, 9]])

In [19]:
#math ops
x

array([[2, 6, 7],
       [3, 6, 9],
       [5, 1, 1]])

In [20]:
y=y+6

NameError: ignored

In [21]:
x**3

array([[  8, 216, 343],
       [ 27, 216, 729],
       [125,   1,   1]])

In [0]:
#final about 